// Generated by https://quicktype.io
export interface RedditImageArray {
    after: string;
    images: object[];
}

export interface ImageObject {
    title: string;
    thumbnail: string;
    url: string;
    permalink: string;
    subreddit: string;
}

