// Generated by https://quicktype.io

export interface UserData {
    kind: Kind;
    data: UserDataObject;
}

export interface UserDataObject {
    approved_at_utc:                  null;
    subreddit:                        string;
    selftext?:                        string;
    author_fullname:                  AuthorFullname;
    saved:                            boolean;
    mod_reason_title:                 null;
    gilded:                           number;
    clicked?:                         boolean;
    title?:                           string;
    link_flair_richtext?:             LinkFlairRichtext[];
    subreddit_name_prefixed:          string;
    hidden?:                          boolean;
    pwls?:                            number | null;
    link_flair_css_class?:            null | string;
    downs:                            number;
    thumbnail_height?:                number;
    top_awarded_type:                 null;
    hide_score?:                      boolean;
    name:                             string;
    quarantine:                       boolean;
    link_flair_text_color?:           LinkFlairTextColor;
    upvote_ratio?:                    number;
    author_flair_background_color:    null;
    subreddit_type:                   SubredditType;
    ups:                              number;
    total_awards_received:            number;
    media_embed?:                     MediaEmbed;
    thumbnail_width?:                 number;
    author_flair_template_id:         null;
    is_original_content?:             boolean;
    user_reports:                     any[];
    secure_media?:                    Media | null;
    is_reddit_media_domain?:          boolean;
    is_meta?:                         boolean;
    category?:                        null;
    secure_media_embed?:              MediaEmbed;
    link_flair_text?:                 null | string;
    can_mod_post:                     boolean;
    score:                            number;
    approved_by:                      null;
    author_premium:                   boolean;
    thumbnail?:                       string;
    edited:                           boolean;
    author_flair_css_class:           null;
    author_flair_richtext:            any[];
    gildings:                         Gildings;
    post_hint?:                       PostHint;
    content_categories?:              null;
    is_self?:                         boolean;
    mod_note:                         null;
    created:                          number;
    link_flair_type?:                 AuthorFlairType;
    wls?:                             number | null;
    removed_by_category?:             null | string;
    banned_by:                        null;
    author_flair_type:                AuthorFlairType;
    domain?:                          Domain;
    allow_live_comments?:             boolean;
    selftext_html?:                   null;
    likes:                            null;
    suggested_sort?:                  null | string;
    banned_at_utc:                    null;
    url_overridden_by_dest?:          string;
    view_count?:                      null;
    archived:                         boolean;
    no_follow:                        boolean;
    is_crosspostable?:                boolean;
    pinned?:                          boolean;
    over_18:                          boolean;
    preview?:                         Preview;
    all_awardings:                    AllAwarding[];
    awarders:                         any[];
    media_only?:                      boolean;
    can_gild:                         boolean;
    spoiler?:                         boolean;
    locked:                           boolean;
    author_flair_text:                null;
    treatment_tags:                   any[];
    visited?:                         boolean;
    removed_by?:                      null;
    num_reports:                      null;
    distinguished:                    null;
    subreddit_id:                     string;
    mod_reason_by:                    null;
    removal_reason:                   null;
    link_flair_background_color?:     LinkFlairBackgroundColor;
    id:                               string;
    is_robot_indexable?:              boolean;
    report_reasons:                   null;
    author:                           Author;
    discussion_type?:                 null;
    num_comments:                     number;
    send_replies:                     boolean;
    whitelist_status?:                WhitelistStatus | null;
    contest_mode?:                    boolean;
    mod_reports:                      any[];
    author_patreon_flair:             boolean;
    author_flair_text_color:          null;
    permalink:                        string;
    parent_whitelist_status?:         WhitelistStatus | null;
    stickied:                         boolean;
    url?:                             string;
    subreddit_subscribers?:           number;
    created_utc:                      number;
    num_crossposts?:                  number;
    media?:                           Media | null;
    is_video?:                        boolean;
    comment_type?:                    null;
    link_id?:                         string;
    replies?:                         string;
    parent_id?:                       string;
    body?:                            string;
    link_title?:                      string;
    is_submitter?:                    boolean;
    body_html?:                       string;
    collapsed_reason?:                null;
    associated_award?:                null;
    score_hidden?:                    boolean;
    link_permalink?:                  string;
    link_author?:                     Author;
    link_url?:                        string;
    collapsed?:                       boolean;
    controversiality?:                number;
    collapsed_because_crowd_control?: null;
    link_flair_template_id?:          string;
}

export interface AllAwarding {
    giver_coin_reward:                    number | null;
    subreddit_id:                         null;
    is_new:                               boolean;
    days_of_drip_extension:               number;
    coin_price:                           number;
    id:                                   string;
    penny_donate:                         number | null;
    award_sub_type:                       string;
    coin_reward:                          number;
    icon_url:                             string;
    days_of_premium:                      number;
    tiers_by_required_awardings:          null;
    resized_icons:                        ResizedIcon[];
    icon_width:                           number;
    static_icon_width:                    number;
    start_date:                           null;
    is_enabled:                           boolean;
    awardings_required_to_grant_benefits: null;
    description:                          string;
    end_date:                             null;
    subreddit_coin_reward:                number;
    count:                                number;
    static_icon_height:                   number;
    name:                                 string;
    resized_static_icons:                 ResizedIcon[];
    icon_format:                          null | string;
    icon_height:                          number;
    penny_price:                          number | null;
    award_type:                           string;
    static_icon_url:                      string;
}

export interface ResizedIcon {
    url:    string;
    width:  number;
    height: number;
}

export enum Author {
    OFLebr18 = "OF_Lebr18",
}

export enum AuthorFlairType {
    Richtext = "richtext",
    Text = "text",
}

export enum AuthorFullname {
    T2Bqm00Wt5 = "t2_bqm00wt5",
}

export enum Domain {
    IImgurCOM = "i.imgur.com",
    RedgifsCOM = "redgifs.com",
}

export interface Gildings {
}

export enum LinkFlairBackgroundColor {
    Ea0027 = "#ea0027",
    Edeff1 = "#edeff1",
    Empty = "",
}

export interface LinkFlairRichtext {
    e: AuthorFlairType;
    t: string;
}

export enum LinkFlairTextColor {
    Dark = "dark",
    Light = "light",
}

export interface Media {
    type:   Domain;
    oembed: Oembed;
}

export interface Oembed {
    provider_url:     string;
    version:          string;
    title:            string;
    type:             string;
    thumbnail_width:  number;
    height:           number;
    width:            number;
    html:             string;
    author_name:      string;
    provider_name:    string;
    thumbnail_url:    string;
    thumbnail_height: number;
    author_url:       string;
}

export interface MediaEmbed {
    content?:          string;
    width?:            number;
    scrolling?:        boolean;
    height?:           number;
    media_domain_url?: string;
}

export enum WhitelistStatus {
    NoAds = "no_ads",
}

export enum PostHint {
    Image = "image",
    Link = "link",
    RichVideo = "rich:video",
}

export interface Preview {
    images:                Image[];
    enabled:               boolean;
    reddit_video_preview?: RedditVideoPreview;
}

export interface Image {
    source:      ResizedIcon;
    resolutions: ResizedIcon[];
    variants:    Variants;
    id:          string;
}

export interface Variants {
    obfuscated: Nsfw;
    nsfw:       Nsfw;
}

export interface Nsfw {
    source:      ResizedIcon;
    resolutions: ResizedIcon[];
}

export interface RedditVideoPreview {
    bitrate_kbps:       number;
    fallback_url:       string;
    height:             number;
    width:              number;
    scrubber_media_url: string;
    dash_url:           string;
    duration:           number;
    hls_url:            string;
    is_gif:             boolean;
    transcoding_status: string;
}

export enum SubredditType {
    Public = "public",
    User = "user",
}

export enum Kind {
    T1 = "t1",
    T3 = "t3",
}
